/**
 * BOSS直聘自动投递训练脚本
 *
 * 运行方式（trainer server + 扩展都要启动）：
 *   npx tsx packages/trainer/src/tasks/boss_apply.ts
 *
 * 功能：对职位列表中的前N个职位点击"立即沟通"，然后点击"留在此页"
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { RemotePage } from '../runner/RemotePage.js'
import { ScriptStore } from '../runner/ScriptStore.js'

const ENTRY_URL = 'https://www.zhipin.com/web/geek/job'
const MAX_JOBS = 5
const SCRIPT_ID = 'boss_apply'

const page = new RemotePage()

async function checkBridgeConnected() {
	const res = await fetch('http://127.0.0.1:3002/api/bridge/status')
	const data = (await res.json()) as { connected: boolean }
	if (!data.connected) {
		console.error('❌ Extension not connected to bridge.')
		console.error('   1. Start trainer: npm run dev:trainer')
		console.error('   2. Load extension in Chrome (dev mode)')
		console.error('   3. Make sure the extension is active (side panel open)')
		process.exit(1)
	}
	console.log('✅ Extension connected')
}

async function explore() {
	console.log('\n=== Phase 1: Explore ===')

	// Navigate to job list
	console.log('Navigating to BOSS直聘 job list...')
	await page.navigate(ENTRY_URL)
	await page.wait(2000)

	const url = await page.getCurrentUrl()
	console.log('Current URL:', url)

	// Get clean HTML to discover selectors
	console.log('\nGetting clean HTML of job list...')
	const html = await page.getCleanHtml()

	// Save HTML to file for inspection
	const htmlPath = join(process.cwd(), 'data', 'boss_explore.html')
	writeFileSync(htmlPath, html)
	console.log(`Saved clean HTML to: ${htmlPath}`)
	console.log('HTML length:', html.length)

	// Print a snippet to see structure
	console.log('\nHTML preview (first 3000 chars):')
	console.log(html.slice(0, 3000))

	return html
}

async function findJobCardSelectors(html: string): Promise<string> {
	// Look for job card patterns in the HTML
	const patterns = ['.job-card-wrap', '.job-card-box', '.job-list-box .job-card', '.search-job-result .job-card']

	for (const selector of patterns) {
		const exists = await page.exists(selector)
		if (exists) {
			console.log(`✅ Found job cards with selector: ${selector}`)
			return selector
		}
	}

	// Fallback: look in HTML for common patterns
	if (html.includes('job-card-wrap')) return '.job-card-wrap'
	if (html.includes('job-card-box')) return '.job-card-box'

	console.log('⚠️  Could not find job card selector automatically, using default')
	return '.job-card-wrap'
}

async function runTask(jobCardSelector: string) {
	console.log('\n=== Phase 2: Execute Task ===')

	await page.navigate(ENTRY_URL)
	await page.wait(2000)

	// Count available job cards
	const cards = await page.queryAll(jobCardSelector, ['text'])
	console.log(`Found ${cards.length} job cards`)

	const maxJobs = Math.min(cards.length, MAX_JOBS)
	let applied = 0
	let skipped = 0

	for (let i = 0; i < maxJobs; i++) {
		console.log(`\n--- Job ${i + 1}/${maxJobs} ---`)

		try {
			// Click on the job card
			await page.clickNth(jobCardSelector, i)
			await page.wait(800)

			// Check if "立即沟通" button exists
			const hasApply = await page.exists('text:立即沟通')
			if (!hasApply) {
				console.log(`  ⚪ No "立即沟通" button, skipping`)
				skipped++
				continue
			}

			// Click "立即沟通"
			console.log('  Clicking 立即沟通...')
			await page.click('text:立即沟通')
			await page.wait(600)

			// Check for "留在此页" modal
			const hasStay = await page.exists('text:留在此页')
			if (hasStay) {
				console.log('  Clicking 留在此页...')
				await page.click('text:留在此页')
				await page.wait(400)
			}

			applied++
			console.log(`  ✅ Applied (total: ${applied})`)
		} catch (err) {
			console.log(`  ❌ Error: ${err instanceof Error ? err.message : String(err)}`)
			skipped++
		}

		await page.wait(500)
	}

	return { applied, skipped, total: maxJobs }
}

async function saveScript(jobCardSelector: string) {
	console.log('\n=== Phase 3: Save Script ===')

	const code = `// Auto-generated by trainer on ${new Date().toISOString().slice(0, 10)}
// Task: BOSS直聘自动投递
const MAX_JOBS = params.maxJobs ? parseInt(params.maxJobs) : 5;
const JOB_CARD = '${jobCardSelector}';

await page.navigate('${ENTRY_URL}');
await page.wait(2000);

const cards = await page.queryAll(JOB_CARD, ['text']);
const maxJobs = Math.min(cards.length, MAX_JOBS);

let applied = 0;
for (let i = 0; i < maxJobs; i++) {
  try {
    await page.clickNth(JOB_CARD, i);
    await page.wait(800);

    if (await page.exists('text:立即沟通')) {
      await page.click('text:立即沟通');
      await page.wait(600);
      if (await page.exists('text:留在此页')) {
        await page.click('text:留在此页');
        await page.wait(400);
      }
      applied++;
      console.log('Applied:', applied);
    }
  } catch (e) {
    console.log('Skip job', i, ':', e.message);
  }
  await page.wait(500);
}
console.log('Done. Applied to', applied, 'jobs.');
`

	const meta = {
		id: SCRIPT_ID,
		name: 'BOSS直聘自动投递',
		description: '对职位列表中的多个职位点击立即沟通，自动跳过无效职位',
		entryUrl: ENTRY_URL,
		params: ['maxJobs'],
	}

	const saved = ScriptStore.save(meta, code)
	console.log(`✅ Script saved: ${saved.file}`)
	console.log(`   ID: ${saved.id}`)
	console.log(`   To run via API: POST /api/scripts/${saved.id}/run`)
	return saved
}

async function main() {
	console.log('🚀 BOSS直聘 Auto-Apply Trainer')
	console.log('================================')

	await checkBridgeConnected()

	// Phase 1: Explore
	const html = await explore()

	// Find job card selectors from the live page
	const jobCardSelector = await findJobCardSelectors(html)

	// Phase 2: Run the task once to verify
	const result = await runTask(jobCardSelector)
	console.log(`\nTask result: applied=${result.applied}, skipped=${result.skipped}`)

	// Phase 3: Save as reusable script
	if (result.applied > 0 || result.skipped < result.total) {
		await saveScript(jobCardSelector)
	} else {
		console.log('⚠️  No jobs were successfully processed. Not saving script.')
		console.log('   Check boss_explore.html for page structure details.')
	}

	console.log('\n✨ Training complete!')
	process.exit(0)
}

main().catch((err) => {
	console.error('Fatal error:', err)
	process.exit(1)
})
